import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar/navbar'
import Homeb from '../components/homebanner/home'
import styles from '../styles/Home.module.css'
import Service from '../components/service/service'
 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>

     
          <Navbar />
          <div className={styles.home}>
          <Homeb imgUrl='/static/banner.jpg' />
           
          </div>
         
          
 
    </div>
  )
}
